name: Notebook Link Comment

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v4.9
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Automated Notebook Link

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Automated Notebook Link
          The following link will open a colab where you can run this pull request.
          <a href="https://colab.research.google.com/github/andraghetti/disco-diffusion/blob/${{ steps.branch-name.outputs.current_branch }}/Disco_Diffusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab"/></a>
        edit-mode: replace